# Generated by Django 4.2.6 on 2023-10-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('images', models.ImageField(null=True, upload_to='estates_imgs/')),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '2. Estates',
            },
        ),
    ]
