# Generated by Django 4.2.6 on 2023-10-25 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
